name = "skane-trafiken-schedule"
pages_build_output_dir = "dist"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "skane-trafiken-db"
database_id = "ed492707-4b2d-4892-acdc-8a104e2c5837"

[[kv_namespaces]]
binding = "KV"
id = "c0586385ad78495fb8bc245751b7515d"
